[[plugins]]
repo = 'Shougo/dein.vim'
hook_add = '''
    nnoremap [:dein:] <Nop>
    nmap <Leader>D [:dein:]
    nnoremap [:dein:]c :<C-u>call dein#clear_state()<CR>
'''

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'
if = 'executable("cc")'

# unite.vim, vimfiler {{{1
# ============================================================================
[[plugins]]
repo = 'tmsanrinsha/unite-ghq'
build = "test -f ~/bin/ghq-list.sh || ln -s `pwd`/bin/ghq-list.sh ~/bin"

[[plugins]]
repo = 'thinca/vim-unite-history'

[[plugins]]
repo = 'ujihisa/unite-locate'

[[plugins]]
repo = 'tacroe/unite-mark'

[[plugins]]
repo = 'tsukkee/unite-tag'

[[plugins]]
repo = 'rhysd/unite-zsh-cdr.vim'

[[plugins]]
repo = 'Shougo/neossh.vim'

[[plugins]]
repo = 'ujihisa/vimshell-ssh'

# neocomplete {{{1
# ============================================================================
[[plugins]]
repo = 'Shougo/neco-syntax'

[[plugins]]
repo = 'ujihisa/neco-look'
# external_commands = 'look'
# vim_version = '7.3.825'

[[plugins]]
repo = 'Shougo/neoinclude.vim'

[[plugins]]
repo = 'Shougo/context_filetype.vim'

# snippet {{{1
# ============================================================================
[[plugins]]
repo = 'Shougo/neosnippet-snippets'

# operator {{{1
# ============================================================================
[[plugins]]
repo = 'kana/vim-operator-user'

[[plugins]]
repo = 'tpope/vim-repeat'

[[plugins]]
repo = 'tpope/vim-surround'

# textobj {{{1
# ============================================================================
[[plugins]]
repo = 'kana/vim-textobj-user'

[[plugins]]
# lazyにすると最初の"*yieでクリップボードではなく、ヤンクされる
repo = 'kana/vim-textobj-entire'

[[plugins]]
repo = 'sgur/vim-textobj-parameter'

[[plugins]]
repo = 'kana/vim-textobj-function'

[[plugins]]
repo = 'kentaro/vim-textobj-function-php'

[[plugins]]
repo = 'kana/vim-textobj-indent'

[[plugins]]
repo = 'rhysd/vim-textobj-conflict'

[[plugins]]
repo = 'osyo-manga/vim-textobj-multiblock'

[[plugins]]
repo = 'anyakichi/vim-textobj-xbrackets'

# gf {{{1
# ============================================================================
[[plugins]]
repo = 'kana/vim-gf-user'

[[plugins]]
repo = 'kana/vim-gf-diff'

# indent {{{1
# ============================================================================
[[plugins]]
repo = 'ciaranm/detectindent'

# 重い
# [[plugins]]
# repo = 'tpope/vim-sleuth'
# }}}

[[plugins]]
repo = 'osyo-manga/vim-anzu'

# [[plugins]]
# repo = 'terryma/vim-multiple-cursors'

[[plugins]]
repo = 'tmsanrinsha/diffchar.vim'

[[plugins]]
repo = 'sudo.vim'

[[plugins]]
repo = 'savevers.vim'

[[plugins]]
repo = 'kopischke/vim-fetch'

[[plugins]]
repo = 'QuickFixCurrentNumber'
depends = 'ingo-library'

[[plugins]]
repo = 'ingo-library'

[[plugins]]
repo = 'majutsushi/tagbar'

[[plugins]]
repo = 'osyo-manga/vital-coaster'

[[plugins]]
repo = 'tmsanrinsha/vim-emacscommandline'

[[plugins]]
repo = 'airblade/vim-rooter'
hook_add = '''
let g:rooter_manual_only = 1
'''

[[plugins]]
repo = 'tpope/vim-fugitive'
augroup = 'fugitive'

[[plugins]]
repo = 'osyo-manga/shabadou.vim'

[[plugins]]
repo = 'rhysd/clever-f.vim'

[[plugins]]
repo = 'LeafCage/foldCC'

[[plugins]]
repo = 'vim-jp/vital.vim'

[[plugins]]
repo = 'thinca/vim-template'

[[plugins]]
repo = 'thinca/vim-singleton'

[[plugins]]
repo = 'itchyny/lightline.vim'
# depends = ['vim-fugitive', 'tagbar', 'vim-anzu']

[[plugins]]
repo = 'thinca/vim-prettyprint'

[[plugins]]
repo = 'PreserveNoEOL'
if = '!exists("&fixeol")'

[[plugins]]
repo = 'mattn/webapi-vim'

# colorscheme {{{1
# ============================================================================
[[plugins]]
repo = 'tmsanrinsha/molokai'
name = 'my_molokai'

[[plugins]]
repo = 'altercation/vim-colors-solarized'

[[plugins]]
repo = 'reedes/vim-colors-pencil'

# }}}

[[plugins]]
repo = 'h1mesuke/vim-alignta'

[[plugins]]
repo = 'vim-scripts/transpose-words'
hook_add = '''
nmap <S-Tab> <Plug>Transposewords
imap <S-Tab> <Plug>Transposewords
let g:transwrd_wordpattern = '\k\+\%(()\)\?'
'''

# filetype {{{1
# ============================================================================
# arduino {{{2
# -----------------------------------------------------------------------------
[[plugins]]
repo = '4Evergreen4/vim-hardy'

# chef {{{2
# ============================================================================
[[plugins]]
repo = 'vadv/vim-chef'

# confluence {{{2
# -----------------------------------------------------------------------------
[[plugins]]
repo = 'confluencewiki.vim'

# graphviz {{{2
# -----------------------------------------------------------------------------
[[plugins]]
repo = 'wannesm/wmgraphviz.vim'

# java {{{2
# -----------------------------------------------------------------------------
[[plugins]]
repo = 'artur-shaik/vim-javacomplete2'

# javascript {{{2
# -----------------------------------------------------------------------------
[[plugins]]
repo = 'pangloss/vim-javascript'

[[plugins]]
repo = 'jelera/vim-javascript-syntax'

[[plugins]]
repo = 'nono/jquery.vim'

[[plugins]]
repo = 'ternjs/tern_for_vim'
build = 'npm install'
if = 'executable("npm")'

# JSON {{{2
# -----------------------------------------------------------------------------
[[plugins]]
repo = 'elzr/vim-json'

# markdown {{{2
# -----------------------------------------------------------------------------
[[plugins]]
repo = 'plasticboy/vim-markdown'

# yaml frontmatterがヘッダーと判定されてしまうのでコメントアウト
# [[plugins]]
# repo = 'nelstrom/vim-markdown-folding'

# MQL4 {{{2
# -----------------------------------------------------------------------------
[[plugins]]
repo = 'vobornik/vim-mql4'

# PHP {{{2
# -----------------------------------------------------------------------------
[[plugins]]
repo = 'shawncplus/phpcomplete.vim'
if = '!$PHP55'

[[plugins]]
repo = 'StanAngeloff/php.vim'

# python {{{2
# -----------------------------------------------------------------------------
[[plugins]]
repo = 'hynek/vim-python-pep8-indent'

# R lang {{{2
# -----------------------------------------------------------------------------
[[plugins]]
repo = 'jcfaria/Vim-R-plugin'

# shell {{{2
# -----------------------------------------------------------------------------
[[plugins]]
repo = 'sh.vim--Cla'

# solidity {{{2
# -----------------------------------------------------------------------------
[[plugins]]
repo = 'tomlion/vim-solidity'

# SQL hive {{{2
# -----------------------------------------------------------------------------
[[plugins]]
repo = 'autowitch/hive.vim'

# tmux {{{2
# -----------------------------------------------------------------------------
[[plugins]]
repo = 'zaiste/tmux.vim'

# toml {{{2
# -----------------------------------------------------------------------------
[[plugins]]
repo = 'cespare/vim-toml'

# twig {{{2
# -----------------------------------------------------------------------------
[[plugins]]
repo = 'evidens/vim-twig'

# vim {{{2
# -----------------------------------------------------------------------------
[[plugins]]
repo = 'ynkdir/vim-vimlparser'

[[plugins]]
repo = 'vim-jp/vimdoc-ja'

[[plugins]]
repo = 'thinca/vim-ft-help_fold'

[[plugins]]
repo = 'thinca/vim-localrc'

# vimperator {{{2
# -----------------------------------------------------------------------------
[[plugins]]
repo = 'vimperator/vimperator.vim'
# }}}
