#!/usr/bin/env bash
set -e
PATH="$HOME/local/bin:/usr/local/bin:$PATH"

if ! ctags --version | grep 'Exuberant Ctags' 1>/dev/null 2>&1; then
    echo 'ctags is not found'
    exit
fi

cd "$(dirname "${BASH_SOURCE:-$0}")"; cd ../../
trap "rm -f .git/tags.$$" EXIT
ctags --tag-relative -R -f .git/tags.$$ --exclude=.git
mv .git/tags.$$ .git/tags
