#!/usr/bin/env bash
set -e
PATH="/Applications/MacVim.app/Contents/MacOS/ctags:/usr/local/bin/ctags:/usr/bin/ctags:$PATH"

if ! ctags --version | grep 'Exuberant Ctags' 1>/dev/null 2>&1; then
    echo 'Exuberant Ctags is not found'
    exit
fi

cd "$(dirname "${BASH_SOURCE:-$0}")"; cd ../../
trap "rm -f .git/tags.$$" EXIT
ctags --tag-relative -R -f .git/tags.$$ --exclude=.git
mv .git/tags.$$ .git/tags
