#!/usr/bin/env bash
set -e

PATH="/Applications/MacVim.app/Contents/MacOS:/usr/local/bin:/usr/bin:$PATH"

if ! ctags --version | grep 'Exuberant Ctags' 1>/dev/null 2>&1; then
    echo 'Exuberant Ctags is not found'
    exit
fi

cd "$(dirname "${BASH_SOURCE:-$0}")"; cd ../../

if test -f .git/tags.* >/dev/null 2>&1; then
  echo 'Already running'
  exit
fi

trap "rm -f .git/tags.$$" EXIT
ctags --tag-relative=yes -R -f .git/tags.$$ --exclude=.git
mv .git/tags.$$ .git/tags

# # フィルタイプごとにわけるのは時間がかかるのでコメントアウト
# cd "$(dirname "${BASH_SOURCE:-$0}")"; cd ../../
# ctags.sh -d .git --tag-relative=yes -R --append=yes --exclude=.git 2>/dev/null
